title: Makoto Takahara
author: Makoto Takahara
url: https://makototakahara.github.io/ # root address of the site
description: > # description of the site (multiple lines allowed)
Hello! I am Makoto Takahara, a statistics student at the University of Toronto. I was born in Japan but bounced around Japan, the United States, Hong Kong, and Canada.
One of my personal passions is baseball: I played for 12 years, I love watching (on a mission to visit all 30 MLB stadiums), and I have a small collection of baseball caps and memorabilia.
In fact, my interest in statistics was sparked by baseball, where data is used to isolate and evaluate player performance. My journey in statistics has taken me into new domains such as societal well-being and finance.
This website is intended, in part, as a portfolio showcasing my projects, capturing the essence of my statistical adventures across various exciting fields!

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

#twitter:
    #username: abhinav # update or delete this
    #card: summary_large_image

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "home.." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: false # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  show_reading_time: true # show number of words and reading time in the blog posts
  show_tags: true # show tags in a blog posts
  # options for "home" page
  home:
    title_projects: Portfolio
    title_misc_list: Details
    title_blog: Blog
    #title_old_projects: Old Projects

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
